#!/usr/bin/perl
use strict;
use warnings;
use Mana::Docker;

getopt({
  outdir => {
    flag => 'outdir',
    default => 'generated',
  },
  destination => {
    flag    => 'destination',
    default => '/var/www/blog.shawn.zone',
  },
}, {
  image => 'blog-frontend',
  rm => 1,
});

my $tempDir = "/tmp/blog-frontend-$$";

actions(
  'build',
  run => [
    mount(
      '.' => '/app',
    ),
    env(
      OUTDIR => $ARGV{outdir},
      BASE_URL => 'https://shawn.dev',
      SITE_NAME => 'shawn.dev',
      SITE_TITLE => 'shawn.dev',
      FEED_TITLE => 'Shawn M Moore',
    ),
    cmd('./bin/generate.pl'),
  ],
  ($ARGV{is_devel} ? () : (
    exec => ['mv', $ARGV{destination}, $tempDir],
    exec => ['mv', $ARGV{outdir}, $ARGV{destination}],
    exec => [['rm', '-r'], $tempDir],
  )),
);
